### ISSUE TITLE
com.nokia.SensorService needs to be changed

### ISSUE THREAD

**Issue by lpotter** [mer-packages/sensorfw#89]
The dbus interface of com.nokia.SensorService is now very out of date, and should be updated to something more relevant like org.mer.SensorService

**Comment by lpotter** [comment]
another name suggestion would be:
org.sensorfw.SensorService

**Comment by chriadam** [comment]
I think org.merproject.sensorfw.SensorService makes the most sense.

**Comment by spiiroin** [comment]
Changing dbus related names breaks backwards compatibility and requires making changes to unknown amount of client sw out there before things work as expected again -> I would not do it just to make things look a bit neater at a level that is in no way visible to users.

But if there is ever a need to change the dbus api itself (i.e. client sw would need to be changed anyway), then changing of the service/interface names could be done without causing extra work.

**Comment by lpotter** [comment]
I know there are bc issues that require some work, but 'nokia' has long gone out of the picture for this software, not to mention a trademarked name. It should have changed when mer took over.
If we don't change it, it will simply remain the same and it bothers me to have the word 'nokia' anywhere in client software not associated with Nokia any longer.

I would not care even if this was kept in a non master branch, or perhaps some env var versioning check or something.

**Comment by lpotter** [comment]
closed and moved to merproject
