### ISSUE TITLE
Shouldn't this repo be moved to git.merproject.org?

### ISSUE THREAD

**Issue by monich** [mer-packages/sensorfw#91]
https://git.merproject.org/mer-core/sensorfw-qt5

It's currently slightly behind this one.

**Comment by lpotter** [comment]
Probably so, but it might take changing the Jolla webhook/CI to point to this if it doesn't already. 
I can add any patches that might be missing over there, and add a note that this is changing places.
If you could make sure the Jolla builds are correct.

**Comment by lpotter** [comment]
As well, I do not seem to be a project member for that repo...

**Comment by lpotter** [comment]
repo was moved
